version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - type: bind
        source: /opt/graphqldb
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      
  indexer:
    image: subsquid/hydra-indexer:3
    restart: unless-stopped
    environment:
      - INDEXER_WORKERS=5
      - DB_NAME=indexer-db
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index*
      - BLOCK_HEIGHT=0
      - WS_PROVIDER_ENDPOINT_URI=ws://192.168.0.154:9944
      - TYPES_JSON=/types.json
    volumes:
      - type: bind
        source: ./types.json
        target: /types.json
    depends_on: 
      - db
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
  
  indexer-api-gateway:
    image: subsquid/hydra-indexer-gateway:3
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=db 
      - WARTHOG_STARTER_DB_PASSWORD=${DB_PASS}
      - WARTHOG_STARTER_DB_PORT=${DB_PORT}
      - WARTHOG_STARTER_DB_USERNAME=${DB_USER}
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
    ports:
      - "4001:4000" # 
    depends_on:
      - redis
      - indexer
    
  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  query-node:
    image: query-node:latest
    restart: unless-stopped
    build: 
      dockerfile: docker/Dockerfile.query-node
      context: ./
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080:${GRAPHQL_SERVER_PORT}"
    depends_on: 
      - db

  processor:
    image: processor:latest
    restart: unless-stopped
    build: 
      dockerfile: docker/Dockerfile.processor
      context: ./
    env_file:
      - .env
    environment:
      - INDEXER_ENDPOINT_URL=http://indexer-api-gateway:4000/graphql
      - DB_HOST=db
      - POLL_INTERVAL_MS=300
      - TYPEORM_HOST=db
      - DEBUG=hydra-processor:*
    command: ["yarn", "processor:start"]