apiVersion: v1
data:
  BATCH_SIZE: "1000"
  BLOCK_WINDOW: "100000"
  DB_HOST: {{ .Values.db_host }}
  DB_NAME: tfgrid-graphql
  DB_PASS: postgres
  DB_PORT: "5432"
  DB_USER: postgres
  DEBUG: index-builder:*
  GRAPHQL_SERVER_HOST: localhost
  GRAPHQL_SERVER_PORT: "4000"
  INDEXER_ENDPOINT_URL: http://10.109.215.154:4010/v1/graphql
  PROJECT_NAME: tfgrid-graphql
  TYPEORM_LOGGING: error
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: processor-env
  name: env
