apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: indexer-status-service
  name: indexer-status-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer-status-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: indexer-status-service
    spec:
      containers:
        - env:
            - name: PORT
              value: "8081"
            - name: REDIS_URI
              value: redis://redis:6379/1
          image: subsquid/hydra-indexer-status-service:4
          name: indexer-status-service
          resources: {}
      restartPolicy: Always
status: {}
