apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: indexer-gateway
  name: indexer-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: indexer-gateway
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: indexer-db
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DEV_MODE
              value: "true"
            - name: HYDRA_INDEXER_STATUS_SERVICE
              value: {{ .Values.indexer_status_service_url }}
          image: subsquid/hydra-indexer-gateway:4
          name: indexer-gateway
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
